import Head from 'next/head'
import Image from 'next/image'
import LandingPage from './LandingPage.jsx/LandingPage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SysDev CodeCamp Tickets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </div>
  )
}
