import Head from 'next/head'
import LandingPage from './LandingPage.jsx/LandingPage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SysDev CodeCamp Ticketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Smiley_Logo.png" />
      </Head>
      <LandingPage />
    </div>
  )
}
